# -*- coding: utf-8 -*-
"""Training_YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgUbpgUZKWndMN7BJzoHb7qCLfSoyrdI
"""

!pip install ultralytics
import ultralytics
ultralytics.checks() # Verifica che la GPU sia attiva

from ultralytics import YOLO

from google.colab import drive
drive.mount('/content/drive')

# shell command copy dataset file
!cp /content/drive/MyDrive/dataset.zip /content/

!unzip -q /content/dataset.zip -d /content/dataset

# check
!ls /content/dataset

!cat /content/dataset/data.yaml

yolo_model = YOLO('yolo11n.pt')

results = yolo_model.train(
    data='/content/dataset/data.yaml',
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    project='waste_recognition_CyberCat',
    name='experiment_2'
)

!zip -r training_results_02.zip /content/waste_recognition_CyberCat/experiment_2

from google.colab import files
files.download('training_results_02.zip')

from google.colab import files
files.upload()

yolo_model = YOLO("best.pt")

results = yolo_model.val(data="/content/dataset/data.yaml", split="test")